-- V1__baseline.sql - current production schema (PostgreSQL).
-- Existing prod DBs: baselineOnMigrate=true + baselineVersion=1 means V1 is
-- marked Baseline and NOT executed; only newer migrations run.
-- New/empty DBs: V1 runs in full below.
-- SQLite is dev-only and is NOT migrated by Flyway.

-- users
CREATE TABLE users (
    id              INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username        VARCHAR(50) NOT NULL,
    encrypted_key   TEXT        NOT NULL,
    public_key      TEXT        NOT NULL,
    private_key     TEXT        NOT NULL,
    signature       TEXT        NOT NULL DEFAULT '',
    donation_amount BIGINT      NOT NULL DEFAULT 0,
    nickname        VARCHAR(50),
    forum_zone      VARCHAR(10) NOT NULL DEFAULT 'PUBLIC',
    can_invite      BOOLEAN     NOT NULL DEFAULT FALSE,
    invite_slots    INTEGER     NOT NULL DEFAULT 0,
    invited_by      INTEGER,
    is_forum_admin  BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_users_invited_by__id
        FOREIGN KEY (invited_by) REFERENCES users (id)
        ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE UNIQUE INDEX users_username_unique ON users (username);

-- broadcasts
CREATE TABLE broadcasts (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sender  INTEGER,
    content TEXT    NOT NULL,
    system  BOOLEAN NOT NULL DEFAULT FALSE,
    "time"  TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_broadcasts_sender__id
        FOREIGN KEY (sender) REFERENCES users (id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX broadcasts_sender_idx       ON broadcasts (sender);
CREATE INDEX broadcasts_system_idx       ON broadcasts (system);
CREATE INDEX broadcasts_time_idx         ON broadcasts ("time");

-- chats
CREATE TABLE chats (
    id               INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name             VARCHAR(255) NOT NULL,
    owner            INTEGER      NOT NULL,
    private          BOOLEAN      NOT NULL,
    is_moment        BOOLEAN      NOT NULL DEFAULT FALSE,
    last_chat_at     TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    burn_time        BIGINT,
    require_approval BOOLEAN      NOT NULL DEFAULT FALSE,
    CONSTRAINT fk_chats_owner__id
        FOREIGN KEY (owner) REFERENCES users (id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX chats_owner_idx ON chats (owner);
-- Exposed emits a partial unique index: only one moment chat per owner.
CREATE UNIQUE INDEX chats_owner_is_moment_unique ON chats (owner) WHERE is_moment = TRUE;

-- chat_members  (composite PK: chat, user)
CREATE TABLE chat_members (
    chat           INTEGER NOT NULL,
    "user"         INTEGER NOT NULL,
    key            TEXT    NOT NULL,
    unread         INTEGER NOT NULL DEFAULT 0,
    do_not_disturb BOOLEAN NOT NULL DEFAULT FALSE,
    CONSTRAINT pk_chat_members PRIMARY KEY (chat, "user"),
    CONSTRAINT fk_chat_members_chat__id
        FOREIGN KEY (chat) REFERENCES chats (id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_chat_members_user__id
        FOREIGN KEY ("user") REFERENCES users (id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX chat_members_chat_idx ON chat_members (chat);
CREATE INDEX chat_members_user_idx ON chat_members ("user");

-- messages
CREATE TABLE messages (
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    content   TEXT      NOT NULL,
    type      VARCHAR(20) NOT NULL DEFAULT 'TEXT',
    "time"    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    chat      INTEGER   NOT NULL,
    sender    INTEGER,
    reply_to BIGINT,
    read_at   TIMESTAMP WITHOUT TIME ZONE,
    burn      BIGINT,
    reactions JSONB,
    CONSTRAINT fk_messages_chat__id
        FOREIGN KEY (chat) REFERENCES chats (id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_messages_sender__id
        FOREIGN KEY (sender) REFERENCES users (id)
        ON DELETE SET NULL ON UPDATE CASCADE,
    CONSTRAINT fk_messages_reply_to__id
        FOREIGN KEY (reply_to) REFERENCES messages (id)
        ON DELETE SET NULL ON UPDATE CASCADE
);
CREATE INDEX messages_chat_idx     ON messages (chat);
CREATE INDEX messages_sender_idx   ON messages (sender);
CREATE INDEX messages_reply_to_idx ON messages (reply_to);
CREATE INDEX messages_read_at_idx  ON messages (read_at);
CREATE INDEX messages_burn_idx     ON messages (burn);
-- Covering index used by getMessages; declared idempotently by Messages.init().
CREATE INDEX IF NOT EXISTS idx_messages_chat_time
    ON messages (chat, "time" DESC)
    INCLUDE (id, content, type, chat, sender, "time", read_at, burn, reactions);

-- forum_boards
CREATE TABLE forum_boards (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(100) NOT NULL,
    description TEXT         NOT NULL DEFAULT '',
    icon        VARCHAR(50)  NOT NULL DEFAULT '',
    zone        VARCHAR(20)  NOT NULL DEFAULT 'PUBLIC',
    sort_order  INTEGER      NOT NULL DEFAULT 0,
    created_at  BIGINT       NOT NULL
);

-- forum_topics
CREATE TABLE forum_topics (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    board_id           BIGINT       NOT NULL,
    zone               VARCHAR(10)  NOT NULL,
    title              TEXT         NOT NULL,
    author_id          INTEGER      NOT NULL,
    is_anonymous       BOOLEAN      NOT NULL DEFAULT FALSE,
    anonymous_name     VARCHAR(50),
    created_at         BIGINT       NOT NULL,
    pinned             BOOLEAN      NOT NULL DEFAULT FALSE,
    locked             BOOLEAN      NOT NULL DEFAULT FALSE,
    view_count         INTEGER      NOT NULL DEFAULT 0,
    last_reply_at      BIGINT,
    last_reply_user_id INTEGER,
    is_deleted         BOOLEAN      NOT NULL DEFAULT FALSE,
    next_floor         INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT fk_forum_topics_board_id__id
        FOREIGN KEY (board_id) REFERENCES forum_boards (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_forum_topics_author_id__id
        FOREIGN KEY (author_id) REFERENCES users (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_forum_topics_last_reply_user_id__id
        FOREIGN KEY (last_reply_user_id) REFERENCES users (id)
        ON DELETE SET NULL
);
CREATE INDEX forum_topics_board_id_idx      ON forum_topics (board_id);
CREATE INDEX forum_topics_author_id_idx     ON forum_topics (author_id);
CREATE INDEX forum_topics_last_reply_at_idx ON forum_topics (last_reply_at);

-- forum_posts
CREATE TABLE forum_posts (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    topic_id         BIGINT      NOT NULL,
    content          TEXT        NOT NULL,
    author_id        INTEGER     NOT NULL,
    is_anonymous     BOOLEAN     NOT NULL DEFAULT FALSE,
    anonymous_name   VARCHAR(50),
    floor_number     INTEGER     NOT NULL,
    created_at       BIGINT      NOT NULL,
    edited_at        BIGINT,
    is_deleted       BOOLEAN     NOT NULL DEFAULT FALSE,
    epoch_id         BIGINT,
    reply_to_post_id BIGINT,
    CONSTRAINT fk_forum_posts_topic_id__id
        FOREIGN KEY (topic_id) REFERENCES forum_topics (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_forum_posts_author_id__id
        FOREIGN KEY (author_id) REFERENCES users (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_forum_posts_epoch_id__id
        FOREIGN KEY (epoch_id) REFERENCES forum_private_epochs (id)
        ON DELETE SET NULL,
    CONSTRAINT fk_forum_posts_reply_to_post_id__id
        FOREIGN KEY (reply_to_post_id) REFERENCES forum_posts (id)
        ON DELETE SET NULL
);
CREATE INDEX forum_posts_topic_id_idx        ON forum_posts (topic_id);
CREATE INDEX forum_posts_author_id_idx       ON forum_posts (author_id);
CREATE INDEX forum_posts_reply_to_post_id_idx ON forum_posts (reply_to_post_id);

-- forum_attachments
CREATE TABLE forum_attachments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id         BIGINT,
    topic_id        BIGINT,
    file_url        TEXT         NOT NULL,
    file_name       VARCHAR(255),
    mime_type       VARCHAR(100),
    file_size       BIGINT       NOT NULL,
    attachment_type VARCHAR(10)  NOT NULL,
    epoch_id        BIGINT,
    sort_order      INTEGER      NOT NULL DEFAULT 0,
    created_at      BIGINT       NOT NULL,
    CONSTRAINT fk_forum_attachments_post_id__id
        FOREIGN KEY (post_id) REFERENCES forum_posts (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_forum_attachments_topic_id__id
        FOREIGN KEY (topic_id) REFERENCES forum_topics (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_forum_attachments_epoch_id__id
        FOREIGN KEY (epoch_id) REFERENCES forum_private_epochs (id)
        ON DELETE SET NULL
);

-- forum_notifications
CREATE TABLE forum_notifications (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id       INTEGER     NOT NULL,
    type          VARCHAR(20) NOT NULL,
    topic_id      BIGINT,
    post_id       BIGINT,
    from_user_id  INTEGER,
    message       TEXT,
    is_read       BOOLEAN     NOT NULL DEFAULT FALSE,
    created_at    BIGINT      NOT NULL,
    CONSTRAINT fk_forum_notifications_user_id__id
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_forum_notifications_topic_id__id
        FOREIGN KEY (topic_id) REFERENCES forum_topics (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_forum_notifications_post_id__id
        FOREIGN KEY (post_id) REFERENCES forum_posts (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_forum_notifications_from_user_id__id
        FOREIGN KEY (from_user_id) REFERENCES users (id)
        ON DELETE CASCADE
);
CREATE INDEX forum_notifications_user_id_is_read_idx ON forum_notifications (user_id, is_read);

-- forum_private_epochs
CREATE TABLE forum_private_epochs (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at    BIGINT      NOT NULL,
    change_type   VARCHAR(20) NOT NULL,
    change_detail TEXT
);

-- forum_private_epoch_keys  (composite PK: epoch_id, user_id)
CREATE TABLE forum_private_epoch_keys (
    epoch_id      BIGINT NOT NULL,
    user_id       INTEGER NOT NULL,
    encrypted_key TEXT   NOT NULL,
    CONSTRAINT pk_forum_private_epoch_keys PRIMARY KEY (epoch_id, user_id),
    CONSTRAINT fk_forum_private_epoch_keys_epoch_id__id
        FOREIGN KEY (epoch_id) REFERENCES forum_private_epochs (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_forum_private_epoch_keys_user_id__id
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE
);

-- forum_protect_keys  (PK: user_id)
CREATE TABLE forum_protect_keys (
    user_id       INTEGER NOT NULL,
    encrypted_key TEXT    NOT NULL,
    updated_at    BIGINT  NOT NULL,
    CONSTRAINT pk_forum_protect_keys PRIMARY KEY (user_id),
    CONSTRAINT fk_forum_protect_keys_user_id__id
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE
);
CREATE UNIQUE INDEX forum_protect_keys_user_id_unique ON forum_protect_keys (user_id);

-- forum_reactions  (composite PK: post_id, user_id, emoji)
CREATE TABLE forum_reactions (
    post_id    BIGINT      NOT NULL,
    user_id    INTEGER     NOT NULL,
    emoji      VARCHAR(10) NOT NULL,
    created_at BIGINT      NOT NULL,
    CONSTRAINT pk_forum_reactions PRIMARY KEY (post_id, user_id, emoji),
    CONSTRAINT fk_forum_reactions_post_id__id
        FOREIGN KEY (post_id) REFERENCES forum_posts (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_forum_reactions_user_id__id
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE
);

-- forum_invitations
CREATE TABLE forum_invitations (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inviter_id   INTEGER     NOT NULL,
    invitee_id   INTEGER     NOT NULL,
    invite_code  VARCHAR(64) NOT NULL,
    status       VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at   BIGINT      NOT NULL,
    used_at      BIGINT,
    expires_at   BIGINT,
    CONSTRAINT fk_forum_invitations_inviter_id__id
        FOREIGN KEY (inviter_id) REFERENCES users (id)
        ON DELETE CASCADE,
    CONSTRAINT fk_forum_invitations_invitee_id__id
        FOREIGN KEY (invitee_id) REFERENCES users (id)
        ON DELETE CASCADE
);
CREATE UNIQUE INDEX forum_invitations_invite_code_unique ON forum_invitations (invite_code);

-- friend_requests
CREATE TABLE friend_requests (
    id         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    from_user  INTEGER     NOT NULL,
    to_user    INTEGER     NOT NULL,
    status     VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    message    VARCHAR(200),
    created_at TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_friend_requests_from_user__id
        FOREIGN KEY (from_user) REFERENCES users (id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_friend_requests_to_user__id
        FOREIGN KEY (to_user) REFERENCES users (id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX friend_requests_from_user_idx ON friend_requests (from_user);
CREATE INDEX friend_requests_to_user_idx   ON friend_requests (to_user);

-- friends  (composite PK: user_a, user_b)
CREATE TABLE friends (
    user_a       INTEGER      NOT NULL,
    user_b       INTEGER      NOT NULL,
    chat         INTEGER      NOT NULL,
    remark_for_a VARCHAR(100),
    remark_for_b VARCHAR(100),
    CONSTRAINT pk_friends PRIMARY KEY (user_a, user_b),
    CONSTRAINT fk_friends_user_a__id
        FOREIGN KEY (user_a) REFERENCES users (id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_friends_user_b__id
        FOREIGN KEY (user_b) REFERENCES users (id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_friends_chat__id
        FOREIGN KEY (chat) REFERENCES chats (id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX friends_user_a_idx ON friends (user_a);
CREATE INDEX friends_user_b_idx ON friends (user_b);
CREATE INDEX friends_chat_idx   ON friends (chat);

-- group_invitations
CREATE TABLE group_invitations (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat          INTEGER     NOT NULL,
    inviter       INTEGER     NOT NULL,
    target_user   INTEGER     NOT NULL,
    encrypted_key TEXT        NOT NULL,
    status        VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    created_at    TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT fk_group_invitations_chat__id
        FOREIGN KEY (chat) REFERENCES chats (id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_group_invitations_inviter__id
        FOREIGN KEY (inviter) REFERENCES users (id)
        ON DELETE CASCADE ON UPDATE CASCADE,
    CONSTRAINT fk_group_invitations_target_user__id
        FOREIGN KEY (target_user) REFERENCES users (id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE INDEX group_invitations_chat_idx ON group_invitations (chat);
