-- V2__sessions.sql - session tokens for HTTP auth (replaces HMAC-per-request).

CREATE TABLE sessions (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER      NOT NULL,
    token_hash  VARCHAR(64)  NOT NULL,
    created_at  BIGINT       NOT NULL,
    expires_at  BIGINT       NOT NULL,
    CONSTRAINT fk_sessions_user_id__id
        FOREIGN KEY (user_id) REFERENCES users (id)
        ON DELETE CASCADE ON UPDATE CASCADE
);
CREATE UNIQUE INDEX sessions_token_hash_unique ON sessions (token_hash);
CREATE INDEX sessions_user_id_idx             ON sessions (user_id);
